version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile

  identityserveraspnetidentity:
    image: ${DOCKER_REGISTRY-}identityserveraspnetidentity
    build:
      context: .
      dockerfile: IdentityServerAspNetIdentity/Dockerfile
    depends_on:
        - sqldata
        - proxy

  webclient:
    image: ${DOCKER_REGISTRY-}webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile
    depends_on:
        - identityserveraspnetidentity

  webapiclient:
    image: ${DOCKER_REGISTRY-}webapiclient
    build:
      context: .
      dockerfile: WebApiClient/Dockerfile
    depends_on:
        - identityserveraspnetidentity

  javascriptclient:
    image: ${DOCKER_REGISTRY-}javascriptclient
    build:
      context: .
      dockerfile: JavaScriptClient/Dockerfile
    depends_on:
        - identityserveraspnetidentity