version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - identityserveraspnetidentity-sqldata:/var/opt/mssql

  proxy:
    ports:
      - "5000:443" 
      - "8000:80"
    restart: always

  identityserveraspnetidentity:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ConnectionStrings__DefaultConnection=Server=sqldata;Database=identityserveraspnetidentity;MultipleActiveResultSets=True;User Id=sa;Password=Pass@word
        - Clients__1__RedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5003/signin-oidc
        - Clients__1__PostLogoutRedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5003/signout-callback-oidc
        - Clients__2__RedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5004/signin-oidc
        - Clients__2__PostLogoutRedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5004/signout-callback-oidc
        - Clients__3__RedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5005/callback
        - Clients__3__PostLogoutRedirectUris__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5005
        - Clients__3__AllowedCorsOrigins__0=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5005
    ports:
        - "5001:443"
        - "8001:80"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webapiclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityUrl=http://identityserveraspnetidentity
      - ReactAppUrl=https://${APP_EXTERNAL_DNS_NAME_OR_IP}:5005
    ports:
      - "5002:443"
      - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityUrl=http://identityserveraspnetidentity
    ports:
      - "5003:443"
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  javascriptclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityUrl=http://identityserveraspnetidentity
      - ApiIdentity=http://${APP_EXTERNAL_DNS_NAME_OR_IP}:5002/api/Identity
    ports:
      - "5004:443"
      - "8004:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  identityserveraspnetidentity-sqldata:
    external: false